import Head from 'next/head';
import Footer from '../footer/footer';
import Navbar from '../navbar/navbar';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>My House Buying</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Navbar />
        {children}
        <Footer />
      </main>
    </>
  );
};

export default Layout;
